# A TOML linter such as https://github.com/tombi-toml/tombi can use this schema to validate your config.
#:schema https://yazi-rs.github.io/schemas/keymap.json

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = 'shell --block -- glow --all -p %h'
desc = "Glow"
