[mgr]
show_hidden = true

[preview]
max_width = 1920
max_height = 1920

[opener]
glow = [
    { run = 'glow -p "$@"', block = true, desc = "View with Glow", for = "unix" },
]
play = [
    { run = 'open "$@"', orphan = true, for = "macos" },
]



