version = 1
agents = []

[trust]
allow_all = true

[[skills]]
name = "write-a-skill"
source = "mattpocock/skills"

[[skills]]
name = "git-committer"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "handoff"
source = "mattpocock/skills"

[[skills]]
name = "dotagents"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "now"
source = "git@github.com:jordi9/skills"
