version = 1
agents = []

[trust]
allow_all = true

[[skills]]
name = "git-committer"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "handoff"
source = "mattpocock/skills"

[[skills]]
name = "dotagents"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "now"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "setup-yaam"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "charter"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "task-plan"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "tdd"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "linear-cli"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "to-stories"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "planning"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "writing-great-skills"
source = "mattpocock/skills"

[[skills]]
name = "to-increments"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "describe-changes"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "jj9"
source = "git@github.com:jordi9/skills"

[[skills]]
name = "grilling"
source = "mattpocock/skills"
