#! /bin/bash

# Install brew

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install homesick

gem install homesick

echo "Now it's time to clone the dotfiles"
homesick clone jordi9/dotfiles
