#!/bin/bash

# SSH config
mkdir .ssh
ln -s ~/Dropbox/.dotfiles_private/.ssh/id_rsa ~/.ssh
ln -s ~/Dropbox/.dotfiles_private/.ssh/id_rsa.pub ~/.ssh
ln -s ~/Dropbox/.dotfiles_private/.ssh/config ~/.ssh

# Private scripts
ln -s ~/Dropbox/.dotfiles_private/bin ~/bin